apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.service: api
    spec:
      containers:
        - args:
            - uvicorn
            - main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "80"
          image: api
          name: api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources: {}
          