apiVersion: v1
kind: Service
metadata:
  labels:
    io.service: api
  name: api
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
  selector:
    io.service: api
status:
  loadBalancer: {}
